server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    client:
      service-url:
        default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
      register-with-eureka: true # 将Eureka Server自身注册到Eureka Server中
      fetch-registry: true # 从Eureka Server中获取服务注册信息
    server:
      eviction-interval-timer-in-ms: 30000 # 清除不可用实例的时间间隔
      enable-self-preservation: true # 启用自我保护模式，防止误删除服务实例
      wait-time-in-ms-when-sync-empty: 0 # 同步空注册表时等待的时间

spring:
  output:
    ansi:
      enabled: always # ansi颜色输出

management:
  tracing:
    sampling:
      probability: 1.0 # 分布式跟踪采样率