spring:
  config:
    import: "optional:configserver:http://config-service:9500"
    activate:
      on-profile: docker
---
spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://localhost:9500"
